### ISSUE TITLE
Creating parts/stock items in inventree from Ki-nTree creates part with off by one quantity

### ISSUE THREAD

**Issue by timmyhadwen** [sparkmicro/Ki-nTree#235] opened 2024-06-06 06:56 UTC
What i did:
- Creating parts by entering in Part Number in search field
- Jumping to InvenTree field to select the right category, quantity and stock location
- Not using KiCad plugin

What happens:
- Each part goes into inventree stock as the quantity of the previous entry.

Create part A with quantity 1 - creates part A with quantity 1
Create part B with quantity 2 - creates part B with quantity 1
Create part C with quantity 3 - creates part C with quantity 2
etc...

**Comment by eeintech** [comment] 2024-06-13 14:16
@timmyhadwen Ummm will need to reproduce and fix this, thanks for reporting it!

**Comment by T0jan** [comment] 2024-06-14 10:55
I can confirm this on Windows and Linux. There seems to be a problem with updating the value while the user is entering it. If you enter a value, switch to the `Create` view and create a part the stock number will be set to whatever was set before in the `Stock Quantity`. If you enter a value, switch to any other view, switch back to the `InvenTree` view and then create the part afterwards the correct quantity is set. It seems like the corresponding background variable is only updated when entering the view, not while exiting or changing the value.

**Comment by T0jan** [comment] 2024-06-14 11:23
And it was as expected, some callbacks were missing, fix is ready: #237

**Comment by T0jan** [comment] 2024-07-08 14:47
fixed in v1.1.1

**Closed by T0jan** 2024-07-08 14:47 UTC
Labels: bug

**Comment by timmyhadwen** [comment] 2024-09-04 01:28
<3
