### ISSUE TITLE
Multiprocessing crash on macOS

### ISSUE THREAD

**Issue by 42CrMo4** [sparkmicro/Ki-nTree#160] opened 2023-06-12 21:27 UTC
I tried to setup the new v1.0.1 (same with v1.0.0) on macOS and was not able to get a connection to inventree. The application is starting and everything was looking good. When I tried to connect to the Inventree instance (private and the public Demo) python crashes and no connection is established. The following Error Message is given in the Terminal:

```bash
objc[83510]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[83510]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

After some googling I was able to find the following Stackoverflow question:
[https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr](https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr)

For a workaround it is mentioned to use an environmental variable `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` to disable a security feature so that the multiprocessing does not lead to a crash. 
This works for me, but I do not think that this is good idea. As mentioned in the answer [https://stackoverflow.com/a/69405247](https://stackoverflow.com/a/69405247) there could be a solution but I do not know if this solution is possible for Ki-nTree.

```python
with multiprocessing.get_context("spawn").Pool() as pool:
   pool.map(annotate,img_urls)
```

My Setup is: 
macOS Catalina 10.15.7
Intel Mac
Python 3.9.16
Flet 0.5.2
Ki-nTree 1.0.1

If you need any other information, I'm happy to help and thank you for the excellent Tool.

**Comment by 42CrMo4** [comment] 2023-06-21 20:08
@eeintech I would love to but don't think I have the knowledge. Nevertheless I will give it a try.

**Comment by eeintech** [comment] 2023-06-22 12:33
@42CrMo4 Happy to give you pointers if needed, sorry I can't help further 😕

**Comment by EvilMustacheTwirl** [comment] 2023-08-22 05:41
This is because apple changed the way objectiveC handles multiprocessing you can solve it by doing the following in terminal:

`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`

`source ~/.zshrc`

Then it should start working again.

**Comment by eeintech** [comment] 2024-02-27 15:05
Closing as won't be able to reproduce (don't have a macbook)

**Closed by eeintech** 2024-02-27 15:05 UTC
Labels: enhancement
