### ISSUE TITLE
Digikey error clientid

### ISSUE THREAD

**Issue by Randomtyper23** [sparkmicro/Ki-nTree#44] opened 2021-07-07 17:36 UTC
Hey all,

Are there any known problems with the linking of the program with the digikey-API? The installation succeeded on my PC, but when i enter the client and secret i get from following the video posted about the digikey API, i get an error (401) saying the clientID is invalid...
Does anyone know how to fix this?

Kind regards

**Comment by eeintech** [comment] 2021-07-07 18:04
@Randomtyper23 Just to be certain, have you followed the steps in this video to create a Digi-Key API instance: https://www.youtube.com/watch?v=OI1EGEc0Ju0

Are you sure it is a "**production**" app, not a sandbox?

Have you copied the Client ID and Key completely?

**Comment by Randomtyper23** [comment] 2021-07-07 18:28
Yes, i follow the video step by step :) 
It also display a production app yeah, and i copied and then manually typed it aswell once, but to no result :(

**Comment by eeintech** [comment] 2021-07-07 18:32
Ok good. Can you copy the error here or post a screenshot?

What browser are you using?

**Comment by stijnloeys** [comment] 2021-07-07 20:05
This is the error i get in chrome (also the browser i use): 
{"ErrorResponseVersion":"3.0.0.0","StatusCode": 401,"ErrorMessage":"Invalid clientId","ErrorDetails":"client_id query parameter has incorrect value. Send valid client_id","RequestId":"26583285-ef0b-41d2-c657-bf0594c1564e","ValidationErrors":[]}

the application says "failed to connect to digi-key Api" and the console says: 
2021-07-07 22:03:32,818 - digikey.oauth.oauth2 -  WARNING: Oauth2 token storage does not exist or malformed, creating new.
WARNING:digikey.oauth.oauth2:Oauth2 token storage does not exist or malformed, creating new.

Thanks in advance!

**Comment by eeintech** [comment] 2021-07-07 20:37
Oh maybe you have previous files that prevents the token to be formed correctly.

Check the path to your `Cache Folder` in the User settings:

![image](https://user-images.githubusercontent.com/4020546/124825209-5234ea80-df41-11eb-8b1e-b318f058115e.png)

then make sure this path does not have files (or delete them) other than two folders `images` and `search`.

Then re-try your Client ID and Key using Ki-nTree "Test" button.

**Comment by stijnloeys** [comment] 2021-07-08 06:23
Hey, I checked the cache folder and there were no files except for the images and search files you mentioned (they were both empty). But they are in a different folder than all the program itself:
![path1](https://user-images.githubusercontent.com/42654949/124872420-881bb280-dfc5-11eb-91ea-05338d5ee08f.PNG)
while the program is in
![path2](https://user-images.githubusercontent.com/42654949/124872435-8f42c080-dfc5-11eb-820b-877d273a6c7b.PNG)
with the following stuff inside:
![3](https://user-images.githubusercontent.com/42654949/124872609-c5804000-dfc5-11eb-9de3-a5ba13724b3d.PNG)

**Comment by eeintech** [comment] 2021-07-08 11:52
@Randomtyper23 This is a really weird one...

Could you send a screenshot of your Digi-Key developer app settings (hiding the ID and Key)?
Maybe the callback URL is giving you some kind of issue.

**Comment by StijnLoeys1999** [comment] 2021-07-08 11:57
![production](https://user-images.githubusercontent.com/61249962/124917637-58d06a00-dff4-11eb-8ac4-185cbf096fa5.PNG)
Did you mean this?

**Comment by eeintech** [comment] 2021-07-08 12:00
Yes, and it looks good indeed.

Do you see any file being generated in your cache folder when launching the Digi-Key API test from Ki-nTree?

**Comment by StijnLoeys1999** [comment] 2021-07-08 12:39
I re-installed it on my desktop and now it works! I truly don't know what I did different, but thanks!
Maybe a final question, how do i get the inventree adress? is that just the URL, because in your video it looks like an IP adress, but I don't have access to the computer it is running on

**Comment by eeintech** [comment] 2021-07-08 13:26
@StijnLoeys1999 Sorry I am confused, are you the same user as @Randomtyper23 and @stijnloeys ?

Yes it is just the URL, if you are running your InvenTree instance locally and did not setup a domain name, then it is just the IP and port in the URL, something like this should work: http://127.0.0.1:8000

**Comment by StijnLoeys1999** [comment] 2021-07-08 13:43
Yeah sorry, I switch computer a lot and everyone apparently has a different github account set-up, sorry for that...
The problem is that it is not setup locally :( the url that i use to access the database is "https://ivt.XXXXX.XXXXX/index/" but that does not work... (XXX's are to hide the site name) (dropping the https:// also does not work)

huge thanks for your help so far by the way! It really looks like an amazing program!

**Comment by eeintech** [comment] 2021-07-08 13:46
What if you drop the `index/` at the end of the URL?

**Comment by StijnLoeys1999** [comment] 2021-07-08 13:48
Also does not work then :/

The terminal says the following: "error connecting to InvenTree server: invalid address, username or password"

**Comment by eeintech** [comment] 2021-07-08 13:51
As you are on Windows, I don't think it is a certificate issue...

So with those exact same username and password, you can login to InvenTree at the "https://ivt.XXXXX.XXXXX/" URL?
I wonder if this is a SSL issue... I will investigate

**Comment by StijnLoeys1999** [comment] 2021-07-08 13:54
Yes I can log in, and thanks!

**Comment by eeintech** [comment] 2021-07-08 14:47
I don't think SSL is the issue, can you try to connect to my InvenTree demo instance?

server: `https://inventree.polarize.xyz/`
username: `visitor`
password: `showmethedemo`

**Comment by StijnLoeys1999** [comment] 2021-07-08 14:49
It worked

**Comment by eeintech** [comment] 2021-07-08 14:58
Do you know which port is the InvenTree instance running on?

I would suggest to try instead: "https://ivt.XXXXX.XXXXX:<PORT>" (replacing `<PORT>` with the actual port)

**Comment by StijnLoeys1999** [comment] 2021-07-08 15:24
I don't sorry :(, I tried all of the most common ports but to no succes (https://hostpapasupport.com/commonly-used-ports/)

**Comment by eeintech** [comment] 2021-07-08 15:36
@StijnLoeys1999 Sorry I don't really know why the API refuses to deliver the token for your URL :(
I'll try to google it later see if anything comes up

**Comment by Randomtyper23** [comment] 2021-07-08 16:50
Ok, no worries, thanks in advance

**Comment by eeintech** [comment] 2021-07-08 18:54
@Randomtyper23 Which server are you using?

For Apache, someone seemed to have a similar issue: https://stackoverflow.com/questions/66336931/django-drf-token-authentication-over-https-ssl

I would suggest to google the name of your server along with "drf api not working ssl"
You may encounter a setting on your server that would allow external requests.

**Comment by eeintech** [comment] 2021-07-08 18:55
Also, this seem to be outside of the scope of Ki-nTree, we have proven that your setup is up and running as you were able to connect to the demo version.

Feel free to update this ticket with your findings, however I won't be able to help much more, sorry :(

**Comment by StijnLoeys1999** [comment] 2021-07-09 07:04
No worries man, thanks for the help

**Comment by eeintech** [comment] 2021-07-09 14:44
Cool, I'm closing but feel free to post updates.

**Closed by eeintech** 2021-07-09 14:44 UTC
